### PR TITLE
feat: allow `htmlproofer` params to be specified

### LINKED ISSUE #13: Add ability to pass flags to htmlproofer
`html-proofer` offers a good number of flags to be specify which tests to enforce. While the defaults assumed in this orb seem sensible, I would like to be able to change them without having to fork the orb.

### PR DESCRIPTION
**Pull request by distributedlock**
Resolves #13 .

### CODE REVIEW

**Comment by FelicianoTech** [comment]
Hi @RanadeepPolavarapu, do you regularly use HTML Proofer and/or this orb? I'm trying to determine if providing orb command parameters for all of the HTML Proofer options will be a better or worse user experience then to simply use the `html-proofer` command directly.

**Comment by distributedlock** [comment]
@abahgat You might be better qualified to answer @felicianotech's question above regarding whether this would be useful to your use case or not. I do see it from both of your perspectives. The way I see it is since `html-proofer` is already a part of this orb, extending it with the params is low risk than removing it outright and having people just invoke the command directly.

**Comment by distributedlock** [comment]
I have merged the new structure from `master` branch as well.

**Comment by FelicianoTech** [comment]
> extending it with the params is low risk than removing it outright and having people just invoke the command directly

The other option is to leave the orb as is not remove it.

I agree though that this is low risk and seemingly worth it. Thank you for your contribution.

**Pull request merged**
