### PR TITLE
Allow additional flags to be passed to Hugo.

### LINKED ISSUE #14: Add ability to pass flags to Hugo
This is slightly different than #13 for my use case. I would like to be able to have hugo build draft pages and pages with future content date (which can be done via command line flag) so that I could run `html-proofer` on the future pages.

The subtle difference with respect to 3, is that you probably would imagine not wanting to do this in a deploy workflow.

### PR DESCRIPTION
**Pull request by abahgat**
This allows users of this orb to tweak Hugo's behavior when building the
site.
Example usage:

    version: 2.1
    orbs:
      hugo: circleci/hugo@0.1
    workflows:
      main:
        jobs:
          - hugo/build:
              version: '0.55'
              hugo-extra-flags: '-DF'

Fixes #14

### CODE REVIEW

**Comment by FelicianoTech** [comment]
Hey @abahgat,

Thank you for your PR, this looks good to me. There is a merge conflict though not that the orb source was reorganized in a different PR. Can you please resolve the merge conflict?

**Comment by abahgat** [comment]
Done, could you please take a look?

Also, was wondering whether this Issue/PR should be tagged as Hacktoberfest/Orbtoberfest? :P

**Comment by abahgat** [comment]
Hey @felicianotech, just checking in: are any changes you'd expect to see in this PR or does it look good to you?

Let me know

**Comment by FelicianoTech** [comment]
This looks good. Thank you.

For Hacktoberfest I'm not sure but I'll label it. For Orbtoberfest, you just need to make sure you submit this PR to the Google Form provided.

**Pull request merged**
